<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-05-06 at 08:00:14.
 */
class conexaoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var conexao
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new conexao;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers conexao::abrirConexao
     * @todo   Implement testAbrirConexao().
     */
    public function testAbrirConexao() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
