<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2015-05-06 at 08:00:21.
 */
class controle_acessoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var controle_acesso
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new controle_acesso;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers controle_acesso::validandoLogin
     * @todo   Implement testValidandoLogin().
     */
    public function testValidandoLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers controle_acesso::salvandoLogin
     * @todo   Implement testSalvandoLogin().
     */
    public function testSalvandoLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers controle_acesso::getRegistro_tabela
     * @todo   Implement testGetRegistro_tabela().
     */
    public function testGetRegistro_tabela() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers controle_acesso::getMsg
     * @todo   Implement testGetMsg().
     */
    public function testGetMsg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers controle_acesso::setEmail
     * @todo   Implement testSetEmail().
     */
    public function testSetEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers controle_acesso::setLogin
     * @todo   Implement testSetLogin().
     */
    public function testSetLogin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers controle_acesso::setSenha
     * @todo   Implement testSetSenha().
     */
    public function testSetSenha() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
