<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-27 at 05:58:54.
 */
class produtoTest extends PHPUnit_Framework_TestCase {

    /**
     * @var produto
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new produto;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers produto::getObject
     * @todo   Implement testGetObject().
     */
    public function testGetObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers produto::getFiltro
     * @todo   Implement testGetFiltro().
     */
    public function testGetFiltro() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers produto::setFiltro
     * @todo   Implement testSetFiltro().
     */
    public function testSetFiltro() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers produto::getProduto
     * @todo   Implement testGetProduto().
     */
    public function testGetProduto() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers produto::setProduto
     * @todo   Implement testSetProduto().
     */
    public function testSetProduto() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
